server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webpress?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root233031
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis
  redis:
    port: 6379
    host: localhost
    password:
    lettuce:
      pool:
        # 最大连接数
        max-active: 200
        # 最大阻塞等待时间
        max-wait: -1ms
        # 最大空闲
        max-idle: 10
        # 最小空闲
        min-idle: 0
  # Mail配置
  mail:
    host: smtp.163.com
    password: OFNEJLTGIUYMJVTS
    username: pdx_jie@163.com
    default-encoding: UTF-8
# swagger
swagger:
  enable: true
# 日志
logging:
  level:
    com.pdx.mapper: debug
# MP配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.pdx.modal.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  logging:
    level: warn

###阿里云OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tCroixxjG2GbLgCVC4Y
      keysecret: jM1gUo6w3p1SqGtHgWURXj6sTcaiCT
      bucketname: edu-2330